GET http://127.0.0.1:5000/product

###
GET http://127.0.0.1:5000/product/63b2ff697f106ed4c6908a5e


###
PATCH http://127.0.0.1:5000/product/63b2ff697f106ed4c6908a5e
Content-Type: application/json

{
        "product" : "Domtrain Hiking Mountain Backpack",
        "price" : "$112.70",
        "category" : "Computer & Laptop",
        "imageURL" : "https://i.ibb.co/JBHQRzP/CTRL-brand-tupperware-bottles.png",
        "rate" : 4.7,
        "kota" : "Kota Bandung",
        "sold" : "390 Sold" 
}
###
POST http://127.0.0.1:5000/product
Content-Type: application/json

{
        "product" : "Overflow.id - Basic plain black t-shirt",
        "price" : "$17.34",
        "category" : "Fashion",
        "imageURL" : "https://i.ibb.co/1Z2kP02/Overflow-id-Basic-plain-black-t-shirt.png",
        "rate" : 4.8,
        "kota" : "Kota Jakarta",
        "sold" : "200 Sold" 
}
###
DELETE http://127.0.0.1:5000/product/63b2f8a01e3361ed2f6362cf